language: python
python:
  - "3.6"
install:
  - pip install django coverage
  - cp cronjobManager/settings_template.py cronjobManager/settings.py
script:
  - coverage run manage.py test
after_success:
  - bash <(curl -s https://codecov.io/bash)


