# Generated by Django 2.0.2 on 2018-03-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=128)),
                ('log_limits', models.IntegerField(default=1024)),
                ('log', models.TextField()),
                ('job_args', models.TextField()),
                ('module_name', models.CharField(max_length=128)),
                ('run_at', models.DateTimeField()),
                ('run_every', models.IntegerField(default=86400)),
                ('notification_method', models.CharField(choices=[('email', 'email')], default='email', max_length=64)),
                ('notification_args', models.TextField()),
            ],
        ),
    ]
