# Generated by Django 2.0.2 on 2018-03-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='notification_args',
        ),
        migrations.RemoveField(
            model_name='job',
            name='notification_method',
        ),
    ]
